### ISSUE TITLE
Test script only runs against currently updated master

### ISSUE THREAD

**Issue by rdruss** [openshiftio-vertx-boosters/vertx-http-booster#56]
In looking at the test.sh script, the application gets configured with this line:

oc new-app --template=vertx-http-booster -p SOURCE_REPOSITORY_URL=https://github.com/openshiftio-vertx-boosters/vertx-http-booster 

which clones the existing repo from master.  This implies that the test script cannot be used for testing changes without having the code checked in and merged.  Perhaps it could be modified to accept the organization location which can be changed to your local repo.  Then you would only have to check in your changes on your own fork to run the tests.

I may be misunderstanding the purpose of the test, though, so I thought I'd put in the issue to have the discussion.

**Comment by cescoffier** [comment]
That's the issue with template - it clones a repository (so changes must be pushed)
The script could be modified to accept a specific repository, like a forked one. Note that by default it must be origin/master, as the CI runs the script.

**Comment by rdruss** [comment]
Ok, so I guess my question is what is the intent of the test.sh script?  Is it to be referenced from some CI that runs, or should it be the means by which a developer tests updates or changes?  If it's the latter, then the script probably should be updated to allow a forked repository to be passed in as an argument.  I can work on that change (and apply it to all the repos), but I wanted to be sure I wasn't misunderstanding the purpose of the script.  :-)

**Comment by cescoffier** [comment]
`test.sh` is our only way to ensure that the template still works as expected. It's mainly run by the CI, but it can be extended to work against any repository if the modifications ensure that, if omitted, it will use origin/master.

**Comment by cescoffier** [comment]
Forgot to mention that each booster has its own `test.sh` and they are all a little bit different...

**Comment by rdruss** [comment]
Tried something simple in fix 57
